server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/DM?serverTimezone=Asia/Shanghai
    #useSSL=false&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: 123456

  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    prefix: classpath:/templates/
    suffix: .html

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    com:
      example:
        test:
          mapper: debug
#uploadPath: E:\upload